name: Create Function Lambda and Api Gateway

on:
  workflow_dispatch:

jobs:
  build-and-deploy-function:
    name: Build and Deploy Funtion Lambda
    runs-on: ubuntu-latest

    environment: production

    env:
      TF_VAR_regionDefault: ${{ vars.REGION_DEFAULT }}
      TF_VAR_projectName: ${{ vars.PROJECT_NAME }}
      TF_VAR_stageName: ${{ vars.STAGE_NAME }}
      TF_VAR_labRole: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./AuthLambda/AuthLambda.csproj

      - name: Build
        run: dotnet build ./AuthLambda/AuthLambda.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./AuthLambda/AuthLambda.csproj --configuration Release /p:PublishReadyToRun=true

      - name: Zip publish folder
        run: zip -r function.zip ./AuthLambda/bin/Release/net8.0/publish/**

      - name: Move zip file to terraform directory
        run: mv ./function.zip ./terraform_lambda/

      - name: List files after zip
        run: ls -la ./terraform_lambda

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.REGION_DEFAULT }}      

      - name: Setup Terraform
        if: success()
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        working-directory: terraform_lambda
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: terraform_lambda
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: terraform_lambda
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform_lambda
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform_lambda
        run: terraform apply -input=false -auto-approve
